global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.149.140:9090']
  - job_name: 'MyApp'
    static_configs:
      - targets: ['192.168.149.140:3000']
